FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY configs configs
COPY src src
COPY docker/entrypoint_server.sh docker/entrypoint_server.sh

RUN chmod +x docker/entrypoint_server.sh

CMD ["./docker/entrypoint_server.sh"]
